Repository kata-containers/agent, pull requests merged in 2018-09, with the labels that each got.

#352 agent: update resources list with the right device major-minor number
  device.go
  device_test.go
Labels: review

#360 channel: add serial yamux channel close timeout
  channel.go
  channel_test.go
Labels: review

#361 update grpc-go dependency
  Gopkg.lock
  Gopkg.toml
  grpc.go
  protocols/client/client.go
  vendor/google.golang.org/grpc/balancer.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/base/base.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/balancer_v1_wrapper.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codec.go
  vendor/google.golang.org/grpc/codes/code_string.go
  vendor/google.golang.org/grpc/codes/codes.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/go16.go
  vendor/google.golang.org/grpc/go17.go
  vendor/google.golang.org/grpc/grpclb.go
  vendor/google.golang.org/grpc/grpclb_picker.go
  vendor/google.golang.org/grpc/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/grpclb_util.go
  vendor/google.golang.org/grpc/interceptor.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/naming/go17.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/transport/control.go
  vendor/google.golang.org/grpc/transport/go16.go
  vendor/google.golang.org/grpc/transport/go17.go
  vendor/google.golang.org/grpc/transport/handler_server.go
  vendor/google.golang.org/grpc/transport/http2_client.go
  vendor/google.golang.org/grpc/transport/http2_server.go
  vendor/google.golang.org/grpc/transport/http_util.go
  vendor/google.golang.org/grpc/transport/transport.go
Labels: review

#350 CI: Add "make proto"
  .ci/run.sh
  Makefile
Labels: review

#369 # Kata Containers 1.3.0-rc1
  VERSION
Labels: review

#364 agent: auto-online hotplug memory
  agent.go
Labels: review

#367 fix uevent related errors
  device.go
  pkg/uevent/uevent.go
Labels: bug, review, stable-candidate

#371 agent: fix the issue of missing close process terminal
  agent.go
  epoll.go
  epoll_test.go
  grpc.go
  mockreaper.go
  reaper.go
Labels: bug, review
